<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(BONELAB_DIR)\Mods\&quot;&#xD;&#xA;COPY $(ProjectDir)$(OutputPath)$(TargetName).pdb &quot;$(BONELAB_DIR)\Mods\&quot;" />
  </Target>

  <ItemGroup>
	  <Reference Include="Iced">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\net6\Iced.dll</HintPath>
	  </Reference>
	  <Reference Include="MelonLoader">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\net6\MelonLoader.dll</HintPath>
	  </Reference>
	  <Reference Include="Il2CppInterop.Common">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
	  </Reference>
	  <Reference Include="Il2CppInterop.Runtime">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
	  </Reference>
	  <Reference Include="0Harmony">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\net6\0Harmony.dll</HintPath>
	  </Reference>

	  <Reference Include="Il2Cppmscorlib">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
		  <HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
  </ItemGroup>

</Project>
